[package]
name = 'LiquidswapLPv05'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0x9cc3c27b8d398ab6fc82cbc9dc6b43bb9164f72da465631628163822662a8580"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "351918d1c8ab13db2b586851c480df1036593cfb"
subdir = "aptos-move/framework/move-stdlib"
