[package]
name = 'LiquidswapLPv05'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0x61d2c22a6cb7831bee0f48363b0eec92369357aece0d1142062f7d5d85c7bef8"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "351918d1c8ab13db2b586851c480df1036593cfb"
subdir = "aptos-move/framework/move-stdlib"
