[package]
name = 'LiquidswapInitv05'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_v05 = "0x0163df34fccbf003ce219d3f1d9e70d140b60622cb9dd47599c25fb2f797ba6e"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "351918d1c8ab13db2b586851c480df1036593cfb"
subdir = "aptos-move/framework/aptos-framework"
